---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin-ingress
spec:
  rules:
  - host: zipkin.project.space
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: zipkin
            port:
              number: 9411
